apiVersion: v1
data:
  enable-vts-status: "true"
  proxy-connect-timeout: "605"
  proxy-next-upstream: error timeout http_502 http_503 http_504
  proxy-read-timeout: "605"
  proxy-send-timeout: "605"
  use-gzip: "true"
  use-http2: "true"
  vts-default-filter-key: $server_name
kind: ConfigMap
metadata:
  annotations:
    note: bootstrap
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  name: nginx-ext-ingress-mtls-external-mtls
  #namespace: kube-ingress

