apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    note: bootstrap
  labels:
    app: nginx-ext-ingress-mtls
    k8s-addon: ingress-nginx.addons.k8s.io
    k8s-app: nginx-ingress-controller
  name: nginx-ext-ingress-mtls
  #namespace: kube-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ext-ingress-mtls
  template:
    metadata:
#      annotations:
#        note: bootstrap
#        prometheus.io/port: "10254"
#        prometheus.io/scrape: "true"
      labels:
        app: nginx-ext-ingress-mtls
        k8s-addon: ingress-nginx.addons.k8s.io
        k8s-app: nginx-ingress-controller
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                - system
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - /nginx-ingress-controller
#        - --default-backend-service=$(POD_NAMESPACE)/nginx-default-backend
#        - --configmap=kube-ingress/ingress-nginx-mtls
        - --configmap=default/nginx-ext-ingress-mtls-external-mtls
        - --publish-service=$(POD_NAMESPACE)/nginx-ext-ingress-mtls
        - --ingress-class=external-mtls
        - --election-id=nginx-ext-ingress-mtls
        - --enable-ssl-passthrough
        - --v=3
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        #image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0
        #image: markcr1.azurecr.io/nginx-ingress-controller:0.30.0
        image: mcr.microsoft.com/oss/kubernetes/ingress/nginx-ingress-controller:1.2.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
#        - containerPort: 8000
#          name: ssl-redirect
#          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
      serviceAccountName: nginx-ingress-controller
      terminationGracePeriodSeconds: 120
